const data = [
  {
    'Campaign ID': 'cg:23842702394230778',
    'Campaign Name': 'Dia de los Muertos',
    'Campaign Status': 'PAUSED',
    'Campaign Objective': 'Conversions',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842702394290778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Tucson-35-55',
    'Ad Set Time Start': '10/18/17 22:30',
    'Ad Set Time Stop': '10/23/17 22:09',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': 'tp:1178478948919858',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': 'INITIATED_CHECKOUT',
    Link:
      'https://www.celebrateforgood.com/dia-de-los-muertos-tea-cocktail-party',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: '',
    'Age Min': 35,
    'Age Max': 55,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        interests: [
          {
            id: '6002949260155',
            name: 'Day of the Dead'
          },
          {
            id: '6004038702209',
            name: "All Souls' Day"
          }
        ]
      },
      {
        interests: [
          {
            id: '6002931949762',
            name: 'Cocktail'
          },
          {
            id: '6003332261828',
            name: 'Alcohol'
          },
          {
            id: '6003409043877',
            name: 'Alcoholic beverages'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'OFFSITE_CONVERSIONS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 7
      },
      {
        event_type: 'VIEW_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'IMPRESSIONS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842702394400778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842702394400778&h=AQDgPo7Rhb0Wqqze',
    'Instagram Preview Link': '',
    'Ad Name': 'Cheers-1',
    Title: 'Dia De Los Muertos Cocktail Party',
    Body:
      'Celebrate life over delicious local food, tea cocktails while enjoying community and giving back to a cause that supports the Mexican culture in Tucson. Find more information below!',
    'Link Description': 'Limited number of tickets available.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'https://www.celebrateforgood.com/dia-de-los-muertos/',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:0322dc1ccdbf8043e73e51aa119df83c',
    'Image Crops': '191x100: (0,48)-(2048,1120)',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Link Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Dia%20de%20los%20Muertos&utm_term=Tucson-35-55&utm_content=Cheers-1',
    'Event ID': '',
    'Video ID': '',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2043109195918578?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842702394230778',
    'Campaign Name': 'Dia de los Muertos',
    'Campaign Status': 'PAUSED',
    'Campaign Objective': 'Conversions',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842702394290778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Tucson-35-55',
    'Ad Set Time Start': '10/18/17 22:30',
    'Ad Set Time Stop': '10/23/17 22:09',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': 'tp:1178478948919858',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': 'INITIATED_CHECKOUT',
    Link:
      'https://www.celebrateforgood.com/dia-de-los-muertos-tea-cocktail-party',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: '',
    'Age Min': 35,
    'Age Max': 55,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        interests: [
          {
            id: '6002949260155',
            name: 'Day of the Dead'
          },
          {
            id: '6004038702209',
            name: "All Souls' Day"
          }
        ]
      },
      {
        interests: [
          {
            id: '6002931949762',
            name: 'Cocktail'
          },
          {
            id: '6003332261828',
            name: 'Alcohol'
          },
          {
            id: '6003409043877',
            name: 'Alcoholic beverages'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'OFFSITE_CONVERSIONS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 7
      },
      {
        event_type: 'VIEW_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'IMPRESSIONS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842702407000778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842702407000778&h=AQAAx4_jONakqcTQ',
    'Instagram Preview Link': '',
    'Ad Name': 'Cheers-2',
    Title: 'Dia De Los Muertos Cocktail Party',
    Body:
      'El Dia de los Muertos (the Day of the Dead), a Mexican celebration, is a day to celebrate, remember and prepare special foods in honor of those who have departed. We will be gathering to celebrate life over delicious local food, tea cocktails while enjoying community and giving back to a cause that supports the Mexican culture in Tucson!',
    'Link Description': 'Limited number of tickets available.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'https://www.celebrateforgood.com/dia-de-los-muertos/',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:0322dc1ccdbf8043e73e51aa119df83c',
    'Image Crops': '191x100: (0,48)-(2048,1120)',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Link Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Dia%20de%20los%20Muertos&utm_term=Tucson-35-55&utm_content=Cheers-2',
    'Event ID': '',
    'Video ID': '',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2043109122585252?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842702394230778',
    'Campaign Name': 'Dia de los Muertos',
    'Campaign Status': 'PAUSED',
    'Campaign Objective': 'Conversions',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842702394290778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Tucson-35-55',
    'Ad Set Time Start': '10/18/17 22:30',
    'Ad Set Time Stop': '10/23/17 22:09',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': 'tp:1178478948919858',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': 'INITIATED_CHECKOUT',
    Link:
      'https://www.celebrateforgood.com/dia-de-los-muertos-tea-cocktail-party',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: '',
    'Age Min': 35,
    'Age Max': 55,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        interests: [
          {
            id: '6002949260155',
            name: 'Day of the Dead'
          },
          {
            id: '6004038702209',
            name: "All Souls' Day"
          }
        ]
      },
      {
        interests: [
          {
            id: '6002931949762',
            name: 'Cocktail'
          },
          {
            id: '6003332261828',
            name: 'Alcohol'
          },
          {
            id: '6003409043877',
            name: 'Alcoholic beverages'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'OFFSITE_CONVERSIONS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 7
      },
      {
        event_type: 'VIEW_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'IMPRESSIONS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842702399160778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842702399160778&h=AQA32AdZhKPWGIBg',
    'Instagram Preview Link': '',
    'Ad Name': 'Video-1',
    Title: 'Dia De Los Muertos Cocktail Party',
    Body:
      'Celebrate life over delicious local food, tea cocktails while enjoying community and giving back to a cause that supports the Mexican culture in Tucson. Find more information below!',
    'Link Description': 'Limited number of tickets available.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'https://www.celebrateforgood.com/dia-de-los-muertos/',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:d75ef0d03e508065a67bca872656d597',
    'Image Crops': '',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Video Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Dia%20de%20los%20Muertos&utm_term=Tucson-35-55&utm_content=Video-1',
    'Event ID': '',
    'Video ID': 'v:2042324662663698',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2043108852585279?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842702394230778',
    'Campaign Name': 'Dia de los Muertos',
    'Campaign Status': 'PAUSED',
    'Campaign Objective': 'Conversions',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842702394290778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Tucson-35-55',
    'Ad Set Time Start': '10/18/17 22:30',
    'Ad Set Time Stop': '10/23/17 22:09',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': 'tp:1178478948919858',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': 'INITIATED_CHECKOUT',
    Link:
      'https://www.celebrateforgood.com/dia-de-los-muertos-tea-cocktail-party',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: '',
    'Age Min': 35,
    'Age Max': 55,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        interests: [
          {
            id: '6002949260155',
            name: 'Day of the Dead'
          },
          {
            id: '6004038702209',
            name: "All Souls' Day"
          }
        ]
      },
      {
        interests: [
          {
            id: '6002931949762',
            name: 'Cocktail'
          },
          {
            id: '6003332261828',
            name: 'Alcohol'
          },
          {
            id: '6003409043877',
            name: 'Alcoholic beverages'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'OFFSITE_CONVERSIONS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 7
      },
      {
        event_type: 'VIEW_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'IMPRESSIONS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842702407010778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842702407010778&h=AQD82_tzYnaJ-0Ob',
    'Instagram Preview Link': '',
    'Ad Name': 'Video-2',
    Title: 'Dia De Los Muertos Cocktail Party',
    Body:
      'El Dia de los Muertos (the Day of the Dead), a Mexican celebration, is a day to celebrate, remember and prepare special foods in honor of those who have departed. We will be gathering to celebrate life over delicious local food, tea cocktails while enjoying community and giving back to a cause that supports the Mexican culture in Tucson!',
    'Link Description': 'Limited number of tickets available.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'https://www.celebrateforgood.com/dia-de-los-muertos/',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:d75ef0d03e508065a67bca872656d597',
    'Image Crops': '',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Video Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Dia%20de%20los%20Muertos&utm_term=Tucson-35-55&utm_content=Video-2',
    'Event ID': '',
    'Video ID': 'v:2042324662663698',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2043108655918632?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842701703370778',
    'Campaign Name': 'Birthday Targets',
    'Campaign Status': 'ACTIVE',
    'Campaign Objective': 'Traffic',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842701703420778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Women-18-45-Dec+Nov',
    'Ad Set Time Start': '10/17/17 23:25',
    'Ad Set Time Stop': '10/23/17 23:07',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': '',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': '',
    Link: 'https://www.celebrateforgood.com/how-it-works/',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home, recent',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: 'Women',
    'Age Min': 18,
    'Age Max': 45,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        life_events: [
          {
            id: '6048810914583',
            name: 'Birthday in December'
          },
          {
            id: '6048810938183',
            name: 'Birthday in November'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'LINK_CLICKS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'LINK_CLICKS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842701706900778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842701706900778&h=AQDFNPKxDK8P2USC',
    'Instagram Preview Link': '',
    'Ad Name': 'Flowers-1',
    Title: 'How It Works',
    Body:
      "You are watching your friends walk out the door, one by one, seemingly pleased with the party you have put on. However, as you close that big wooden door and turn around, you realize there is a pile of dishes the size of Mount Kilimanjaro, you have to be up early for work, and you don't ACTUALLY remember a moment of your own party (because you had to make sure every detail was perfect). What if you could be present at your celebration, have someone else do the set up and take down, and have a percent go to charity? That's exactly what we do. Find out more about partying with a purpose, (without the hassle) by clicking below!",
    'Link Description': 'Your party. We Plan it.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'celebrateforgood.com/how-it-works',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:66ad4dc7123d6abbc4f59d50d5d63466',
    'Image Crops': '',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Link Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Birthday%20Targets&utm_term=Women-18-45-Dec%2BNov&utm_content=Flowers%201',
    'Event ID': '',
    'Video ID': '',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [
      {
        'action.type': ['offsite_conversion']
      }
    ],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2042637359299095?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842701703370778',
    'Campaign Name': 'Birthday Targets',
    'Campaign Status': 'ACTIVE',
    'Campaign Objective': 'Traffic',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842701703420778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Women-18-45-Dec+Nov',
    'Ad Set Time Start': '10/17/17 23:25',
    'Ad Set Time Stop': '10/23/17 23:07',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': '',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': '',
    Link: 'https://www.celebrateforgood.com/how-it-works/',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home, recent',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: 'Women',
    'Age Min': 18,
    'Age Max': 45,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        life_events: [
          {
            id: '6048810914583',
            name: 'Birthday in December'
          },
          {
            id: '6048810938183',
            name: 'Birthday in November'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'LINK_CLICKS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'LINK_CLICKS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842701703560778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842701703560778&h=AQDyxdNXk12_wOIt',
    'Instagram Preview Link': '',
    'Ad Name': 'Party-1',
    Title: 'How It Works',
    Body:
      "You are watching your friends walk out the door, one by one, seemingly pleased with the party you have put on. However, as you close that big wooden door and turn around, you realize there is a pile of dishes the size of Mount Kilimanjaro, you have to be up early for work, and you don't ACTUALLY remember a moment of your own party (because you had to make sure every detail was perfect). What if you could be present at your celebration, have someone else do the set up and take down, and have a percent go to charity? That's exactly what we do. Find out more about partying with a purpose, (without the hassle) by clicking below!",
    'Link Description': 'Your party. We Plan it.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'celebrateforgood.com/how-it-works',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:f55a5140e093ed45a610e0e606cafecb',
    'Image Crops': '',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Link Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Birthday%20Targets&utm_term=Women-18-45-Dec%2BNov&utm_content=Party%201',
    'Event ID': '',
    'Video ID': '',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [
      {
        'action.type': ['offsite_conversion']
      }
    ],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/2042633672632797?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  },
  {
    'Campaign ID': 'cg:23842701703370778',
    'Campaign Name': 'Birthday Targets',
    'Campaign Status': 'ACTIVE',
    'Campaign Objective': 'Traffic',
    'Buying Type': 'AUCTION',
    'Campaign Spend Limit': '',
    'Campaign Daily Budget': '',
    'Campaign Lifetime Budget': '',
    'Campaign Bid Strategy': '',
    Tags: '',
    'Product Catalog ID': '',
    'Campaign Page ID': '',
    'Ad Set ID': 'c:23842701703420778',
    'Ad Set Run Status': 'ACTIVE',
    'Ad Set Lifetime Impressions': 0,
    'Ad Set Name': 'Women-18-45-Dec+Nov',
    'Ad Set Time Start': '10/17/17 23:25',
    'Ad Set Time Stop': '10/23/17 23:07',
    'Ad Set Daily Budget': 10,
    'Destination Type': 'UNDEFINED',
    'Ad Set Lifetime Budget': 0,
    'Rate Card': '',
    'Ad Set Schedule': '',
    'Use Accelerated Delivery': 'No',
    'Frequency Control': '',
    'Ad Set Minimum Spend Limit': '',
    'Ad Set Maximum Spend Limit': '',
    'Link Object ID': 'o:1818914131671420',
    'Optimized Conversion Tracking Pixels': '',
    'Optimized Custom Conversion ID': '',
    'Optimized Pixel Rule': '',
    'Optimized Event': '',
    Link: 'https://www.celebrateforgood.com/how-it-works/',
    'Application ID': '',
    'Product Set ID': '',
    'Place Page Set ID': '',
    'Object Store URL': '',
    'Offer ID': '',
    Countries: '',
    Cities: '',
    Regions: '',
    'Electoral Districts': '',
    Zip: '',
    Addresses: '',
    'Geo Markets (DMA)': 'Tucson (Sierra Vista)',
    'Global Regions': '',
    'Location Types': 'home, recent',
    'Location Set IDs': '',
    'Excluded Countries': '',
    'Excluded Cities': '',
    'Excluded Regions': '',
    'Excluded Electoral Districts': '',
    'Excluded Zip': '',
    'Excluded Addresses': '',
    'Excluded Geo Markets (DMA)': '',
    'Excluded Global Regions': '',
    Gender: 'Women',
    'Age Min': 18,
    'Age Max': 45,
    'Education Status': '',
    'Fields of Study': '',
    'Education Schools': '',
    'Work Job Titles': '',
    'Work Employers': '',
    'College Start Year': '',
    'College End Year': '',
    'Interested In': '',
    Relationship: '',
    'Family Statuses': '',
    Industries: '',
    'Life Events': '',
    Politics: '',
    Income: '',
    'Net Worth': '',
    'Home Type': '',
    'Home Ownership': '',
    'Home Value': '',
    'Multicultural Affinity': '',
    Generation: '',
    'Household Composition': '',
    Moms: '',
    'Office Type': '',
    Behaviors: '',
    Connections: '',
    'Excluded Connections': '',
    'Friends of Connections': '',
    Locales: '',
    'Site Category': '',
    'Unified Interests': '',
    'Excluded User AdClusters': '',
    'Broad Category Clusters': '',
    'Targeting Categories - ALL OF': '',
    'Custom Audiences': '',
    'Excluded Custom Audiences': '',
    'Flexible Inclusions': [
      {
        life_events: [
          {
            id: '6048810914583',
            name: 'Birthday in December'
          },
          {
            id: '6048810938183',
            name: 'Birthday in November'
          }
        ]
      },
      {
        interests: [
          {
            id: '6003222044676',
            name: 'Charitable organization'
          },
          {
            id: '6003422719241',
            name: 'Charity and causes'
          }
        ]
      }
    ],
    'Flexible Exclusions': '',
    'Targeting Optimization': 'none',
    'Product Audience Specs': '',
    'Excluded Product Audience Specs': '',
    'Targeted Business Locations': '',
    'Publisher Platforms': 'facebook',
    'Facebook Positions': 'feed',
    'Instagram Positions': '',
    'Audience Network Positions': '',
    'Messenger Positions': '',
    'Device Platforms': 'mobile, desktop',
    'User Device': '',
    'Excluded User Device': '',
    'User Operating System': '',
    'User OS Version': '',
    'Wireless Carrier': '',
    'Excluded Publisher Categories': '',
    'Optimization Goal': 'LINK_CLICKS',
    'Attribution Spec': [
      {
        event_type: 'CLICK_THROUGH',
        window_days: 1
      }
    ],
    'Billing Event': 'LINK_CLICKS',
    'Bid Amount': '',
    'Ad Set Bid Strategy': 'Lowest Cost',
    'Story ID': '',
    'Ad ID': 'a:23842701704140778',
    'Ad Status': 'ACTIVE',
    'Preview Link':
      'https://www.facebook.com/?feed_demo_ad=23842701704140778&h=AQBSsvfy4EhR8HHN',
    'Instagram Preview Link': '',
    'Ad Name': 'Video-1',
    Title: 'How It Works',
    Body:
      "You are watching your friends walk out the door, one by one, seemingly pleased with the party you have put on. However, as you close that big wooden door and turn around, you realize there is a pile of dishes the size of Mount Kilimanjaro, you have to be up early for work, and you don't ACTUALLY remember a moment of your own party (because you had to make sure every detail was perfect). What if you could be present at your celebration, have someone else do the set up and take down, and have a percent go to charity? That's exactly what we do. Find out more about partying with a purpose, (without the hassle) by clicking below!",
    'Link Description': 'Your party. We Plan it.',
    'Retailer IDs': '',
    'Post Click Item Headline': '',
    'Post Click Item Description': '',
    'Display Link': 'celebrateforgood.com/how-it-works',
    'Conversion Tracking Pixels': 'tp:1178478948919858',
    'Image Hash': '1624157600969567:4d82a51991a3095c66ef00288e787fc0',
    'Image Crops': '',
    'Video Thumbnail URL': '',
    'Instagram Platform Image Hash': '',
    'Instagram Platform Image Crops': '',
    'Instagram Platform Image URL': '',
    'Creative Type': 'Video Page Post Ad',
    'URL Tags':
      'utm_source=facebook&utm_medium=cpc&utm_campaign=Birthday%20Targets&utm_term=Women-18-45-Dec%2BNov&utm_content=Video%201',
    'Event ID': '',
    'Video ID': 'v:10155578581626006',
    'Instagram Account ID': '',
    'Mobile App Deep Link': '',
    'Product Link': '',
    'Call to Action': 'LEARN_MORE',
    'Call to Action Link': '',
    'Additional Custom Tracking Specs': [
      {
        'action.type': ['offsite_conversion']
      }
    ],
    'Video Retargeting': 'No',
    'Lead Form ID': '',
    Permalink:
      'https://business.facebook.com/1818914131671420/posts/10155578613731006?business_id=1302633089788688',
    'Force Single Link': '',
    'Dynamic Ad Voice': '',
    'Creative Optimization': '',
    'Template URL': '',
    'Android App Name': '',
    'Android Package Name': '',
    'Deep Link For Android': '',
    'Facebook App ID': '',
    'iOS App Name': '',
    'iOS App Store ID': '',
    'Deep Link For iOS': '',
    'iPad App Name': '',
    'iPad App Store ID': '',
    'Deep Link For iPad': '',
    'iPhone App Name': '',
    'iPhone App Store ID': '',
    'Deep Link For iPhone': '',
    'Deep link to website': '',
    'Windows Store ID': '',
    'Windows App Name': '',
    'Deep Link For Windows Phone': '',
    'Add End Card': '',
    'Dynamic Ads Ad Context': '',
    'Page Welcome Message': '',
    'App Destination': '',
    'Use Page as Actor': 'No',
    'Image Overlay Template': '',
    'Image Overlay Text Type': '',
    'Image Overlay Text Font': '',
    'Image Overlay Position': '',
    'Image Overlay Theme Color': '',
    'Image Overlay Float With Margin': '',
    'Product 1 - Link': '',
    'Product 1 - Name': '',
    'Product 1 - Description': '',
    'Product 1 - Image Hash': '',
    'Product 1 - Image Crops': '',
    'Product 1 - Video ID': '',
    'Product 1 - Mobile App Deep Link': '',
    'Product 1 - Display Link': '',
    'Product 1 - Place Data': '',
    'Product 1 - Is Static Card': '',
    'Product 2 - Link': '',
    'Product 2 - Name': '',
    'Product 2 - Description': '',
    'Product 2 - Image Hash': '',
    'Product 2 - Image Crops': '',
    'Product 2 - Video ID': '',
    'Product 2 - Mobile App Deep Link': '',
    'Product 2 - Display Link': '',
    'Product 2 - Place Data': '',
    'Product 2 - Is Static Card': '',
    'Product 3 - Link': '',
    'Product 3 - Name': '',
    'Product 3 - Description': '',
    'Product 3 - Image Hash': '',
    'Product 3 - Image Crops': '',
    'Product 3 - Video ID': '',
    'Product 3 - Mobile App Deep Link': '',
    'Product 3 - Display Link': '',
    'Product 3 - Place Data': '',
    'Product 3 - Is Static Card': '',
    'Product 4 - Link': '',
    'Product 4 - Name': '',
    'Product 4 - Description': '',
    'Product 4 - Image Hash': '',
    'Product 4 - Image Crops': '',
    'Product 4 - Video ID': '',
    'Product 4 - Mobile App Deep Link': '',
    'Product 4 - Display Link': '',
    'Product 4 - Place Data': '',
    'Product 4 - Is Static Card': '',
    'Product 5 - Link': '',
    'Product 5 - Name': '',
    'Product 5 - Description': '',
    'Product 5 - Image Hash': '',
    'Product 5 - Image Crops': '',
    'Product 5 - Video ID': '',
    'Product 5 - Mobile App Deep Link': '',
    'Product 5 - Display Link': '',
    'Product 5 - Place Data': '',
    'Product 5 - Is Static Card': '',
    'Product 6 - Link': '',
    'Product 6 - Name': '',
    'Product 6 - Description': '',
    'Product 6 - Image Hash': '',
    'Product 6 - Image Crops': '',
    'Product 6 - Video ID': '',
    'Product 6 - Mobile App Deep Link': '',
    'Product 6 - Display Link': '',
    'Product 6 - Place Data': '',
    'Product 6 - Is Static Card': '',
    'Product 7 - Link': '',
    'Product 7 - Name': '',
    'Product 7 - Description': '',
    'Product 7 - Image Hash': '',
    'Product 7 - Image Crops': '',
    'Product 7 - Video ID': '',
    'Product 7 - Mobile App Deep Link': '',
    'Product 7 - Display Link': '',
    'Product 7 - Place Data': '',
    'Product 7 - Is Static Card': '',
    'Product 8 - Link': '',
    'Product 8 - Name': '',
    'Product 8 - Description': '',
    'Product 8 - Image Hash': '',
    'Product 8 - Image Crops': '',
    'Product 8 - Video ID': '',
    'Product 8 - Mobile App Deep Link': '',
    'Product 8 - Display Link': '',
    'Product 8 - Place Data': '',
    'Product 8 - Is Static Card': '',
    'Product 9 - Link': '',
    'Product 9 - Name': '',
    'Product 9 - Description': '',
    'Product 9 - Image Hash': '',
    'Product 9 - Image Crops': '',
    'Product 9 - Video ID': '',
    'Product 9 - Mobile App Deep Link': '',
    'Product 9 - Display Link': '',
    'Product 9 - Place Data': '',
    'Product 9 - Is Static Card': '',
    'Product 10 - Link': '',
    'Product 10 - Name': '',
    'Product 10 - Description': '',
    'Product 10 - Image Hash': '',
    'Product 10 - Image Crops': '',
    'Product 10 - Video ID': '',
    'Product 10 - Mobile App Deep Link': '',
    'Product 10 - Display Link': '',
    'Product 10 - Place Data': '',
    'Product 10 - Is Static Card': '',
    Image: ''
  }
];

module.exports = data;
